#!/usr/bin/env python3
"""gen_geom_cleanup.py -- geometry_cleanup LARGE validation models (STEP solids).

Two scenarios that the geometry_cleanup module must classify and repair:

  A  GeomCleanup_ChamferComplex.step
     Cast-style ribbed bracket (100x80x30 body + bosses + ribs), generated by
     boolean union of primitives, then per-edge chamfers (1..3 mm) and fillets
     (r=0.5..5).  One edge carries an out-of-range fillet radius (>5) as a
     negative control for the classifier.  Multiple through holes.

  B  GeomCleanup_PocketComplex.step
     pocket_plate 200x150x6 with 32 shallow counterbore pockets (depth 1.0~2.5
     < t/2, cb radius 4~12 > hole radius 2~6, regular gradient grid) + 10 plain
     through holes + 2 DEEP counterbores (depth 4 > t/2) that the classifier
     must REJECT.

Module parameters mirrored here:
    fillet_max_r=5, max_chain_depth=6, area_growth_ratio=2.5, stitch_tolerance=0.2.

Units mm.  Built with cadquery (OCCT).  Deterministic.
"""

from __future__ import annotations

import os
import sys
from typing import Dict, List, Tuple

import cadquery as cq

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common
import steplib as S

PARAMS = {
    "fillet_max_r": 5.0,
    "max_chain_depth": 6,
    "area_growth_ratio": 2.5,
    "stitch_tolerance": 0.2,
    "chamfer_range_mm": (1.0, 3.0),
    "negative_fillet_radius_mm": 7.0,  # > fillet_max_r
}

MAIN_BODY = (100.0, 80.0, 30.0)  # W x H x T
BOSS_D = 30.0
BOSS_H = 12.0


def _try_add(result, sel, radius, is_fillet=True):
    """Apply a chamfer or fillet to the edges matching `sel`, falling back to
    halved radii (and finally None) on OCCT failure -- robustness is the
    priority.  Returns the (possibly unchanged) result and whether it applied."""
    for rr in (radius, radius * 0.5, radius * 0.25, -1.0):
        if rr < 0:
            return result, False
        try:
            if is_fillet:
                return result.edges(sel).fillet(rr), True
            return result.edges(sel).chamfer(rr), True
        except Exception:
            continue
    return result, False


def _build_chamfer_bracket() -> cq.Workplane:
    """Cast-style ribbed bracket: body + 4 bosses + 2 ribs, union'ed, then
    chamfers and edge fillets (with one >5mm negative), plus through holes."""
    hw, hh, ht = MAIN_BODY[0] / 2.0, MAIN_BODY[1] / 2.0, MAIN_BODY[2]
    body = cq.Workplane("XY").box(*MAIN_BODY).translate((0.0, 0.0, ht / 2.0))

    # corner bosses
    boss_pts = [(-hw + 22.0, hh - 22.0), (hw - 22.0, hh - 22.0),
                (-hw + 22.0, -hh + 22.0), (hw - 22.0, -hh + 22.0)]
    for px, py in boss_pts:
        cyl = cq.Workplane("XY").circle(BOSS_D / 2.0).extrude(BOSS_H).translate((px, py, ht))
        body = body.union(cyl)

    # two central bosses (extra faces)
    for px in (0.0,):
        for py in (-hh + 18.0,):
            cyl = cq.Workplane("XY").circle(20.0 / 2.0).extrude(18.0).translate((px, py, ht))
            body = body.union(cyl)

    # longitudinal ribs on the top (2) + transverse rib (1)
    for px in (-hw + 30.0, hw - 30.0):
        rib = cq.Workplane("XY").box(10.0, 2 * (hh - 24.0), 6.0).translate((px, 0.0, ht + 3.0))
        body = body.union(rib)
    rib2 = cq.Workplane("XY").box(2 * (hw - 40.0), 10.0, 6.0).translate((0.0, hh - 10.0, ht + 3.0))
    body = body.union(rib2)

    # two edge pads on the foot (extra vertical faces)
    for px in (-hw + 14.0, hw - 14.0):
        pad = cq.Workplane("XY").box(12.0, 12.0, 10.0).translate((px, -hh - 6.0, 5.0))
        body = body.union(pad)

    # perimeter foot flange (stepped base) adds faces + makes it cast-like
    foot = cq.Workplane("XY").box(hw * 2 + 16.0, hh * 2 + 16.0, 6.0).translate((0.0, 0.0, 3.0))
    body = body.union(foot)

    # ---- chamfers (1..3 mm): bosses top rim + foot outer edges ------------
    for px, py in boss_pts:
        top = body.faces(cq.selectors.NearestToPointSelector((px, py, ht + BOSS_H))).val()
        o = top.Center()
        body, _ = _try_add(body, cq.selectors.NearestToPointSelector((o.x, o.y, o.z)), 1.5, is_fillet=False)

    # ---- fillets (0.5..5): edges where ribs meet the body top -------------
    for px in (-hw + 30.0, hw - 30.0):
        rib_side_mid = (px, 0.0, ht + 3.0)
        body, _ = _try_add(body, cq.selectors.NearestToPointSelector(rib_side_mid), 2.0, is_fillet=True)
    body, _ = _try_add(body, cq.selectors.NearestToPointSelector((0.0, 0.0, ht + 3.0)), 3.0, is_fillet=True)
    # longitudinal boss-to-foot edges: down the outer sides
    body, _ = _try_add(body, cq.selectors.NearestToPointSelector((hw, 0.0, 3.0)), 1.2, is_fillet=True)
    body, _ = _try_add(body, cq.selectors.NearestToPointSelector((-hw, 0.0, 3.0)), 1.2, is_fillet=True)
    body, _ = _try_add(body, cq.selectors.NearestToPointSelector((0.0, hh, 3.0)), 0.8, is_fillet=True)

    # ---- NEGATIVE: edge with fillet radius 7 (> fillet_max_r=5) ------------
    body, applied = _try_add(body, cq.selectors.NearestToPointSelector((0.0, -hh, 3.0)),
                             PARAMS["negative_fillet_radius_mm"], is_fillet=True)
    if not applied:
        # geometry must stay a valid single solid regardless of the reject case
        body = body

    # ---- through holes (8) on bosses / central web -------------------------
    holes = [(-hw + 22.0, hh - 22.0, 12.0), (hw - 22.0, hh - 22.0, 12.0),
             (-hw + 22.0, -hh + 22.0, 12.0), (hw - 22.0, -hh + 22.0, 12.0),
             (0.0, hh - 22.0, 10.0), (0.0, -hh + 18.0, 8.0),
             (0.0, 20.0, 10.0), (0.0, -20.0, 10.0)]
    body = S.drill(body, holes, ">Z")
    return body


def _build_pocket_plate() -> Tuple[cq.Workplane, List[Dict], List[Dict], List[Dict]]:
    """Pocket plate: returns (part, pockets, through_holes, deep_pockets)."""
    w, h, t = 200.0, 150.0, 6.0
    pockets: List[Tuple[float, float, float, float, float]] = []
    pocket_meta: List[Dict] = []
    cols, rows = 8, 4
    xs = [-87.5 + c * 25.0 for c in range(cols)]
    ys = [-37.5 + r * 25.0 for r in range(rows)]
    k = 0
    for y in ys:
        for x in xs:
            hole_r = 2.0 + 4.0 * (k / 31.0)          # 2..6 (radius)
            cb_r = max(4.0, hole_r + 2.0 + 4.0 * (k / 31.0))  # 4..12 (radius), > hole_r
            cb_depth = 1.0 + 1.5 * (k / 31.0)        # 1.0..2.5 (< t/2=3)
            pockets.append((x, y, 2.0 * hole_r, 2.0 * cb_r, cb_depth))
            pocket_meta.append({"x": round(x, 2), "y": round(y, 2),
                                "hole_d": round(2 * hole_r, 2), "cb_d": round(2 * cb_r, 2),
                                "cb_depth": round(cb_depth, 2),
                                "shape": "counterbore", "classifier": "ACCEPT"})
            k += 1

    # 10 plain through holes in the surrounding plate areas
    through_holes: List[Tuple[float, float, float]] = []
    through_meta: List[Dict] = []
    th_pts = [(0.0, -90.0, 10.0), (-160.0, 0.0, 10.0), (160.0, 0.0, 10.0),
              (-160.0, 80.0, 8.0), (160.0, 80.0, 8.0), (-160.0, -80.0, 8.0),
              (160.0, -80.0, 8.0), (-40.0, 100.0, 8.0), (40.0, 100.0, 8.0),
              (0.0, -110.0, 8.0)]
    for x, y, d in th_pts:
        through_holes.append((x, y, d))
        through_meta.append({"x": x, "y": y, "diameter": d, "shape": "through", "classifier": "ACCEPT"})

    # 2 DEEP counterbores (depth 4 > t/2=3) -- classifier must REJECT
    deep_pockets: List[Dict] = []
    deep_pts = [(-60.0, 0.0, 6.0, 16.0, 4.0), (60.0, 0.0, 6.0, 16.0, 4.0)]
    for x, y, hd, cbd, dep in deep_pts:
        pockets.append((x, y, hd, cbd, dep))
        deep_pockets.append({"x": x, "y": y, "hole_d": hd, "cb_d": cbd,
                             "cb_depth": dep, "shape": "counterbore_deep",
                             "classifier": "REJECT"})

    part = S.pocket_plate(w, h, t, pockets, holes=through_holes)
    return part, pocket_meta, through_meta, deep_pockets


def main() -> int:
    outdir = common.model_dir("geom_cleanup_multi_feature")

    # ---- A: chamfer complex bracket ---------------------------------------
    bracket = _build_chamfer_bracket()
    info = S.shape_info(bracket)
    if info["solids"] != 1:
        raise ValueError("chamfer bracket: expected 1 solid, got {}".format(info["solids"]))
    path_a = outdir / "GeomCleanup_ChamferComplex.step"
    S.export_step(bracket, str(path_a), "GeomCleanup_ChamferComplex")
    info_a = S.verify_step(str(path_a))
    if info_a["solids"] != 1:
        raise ValueError("chamfer bracket step did not round-trip a solid")
    if info_a["faces"] < 60:
        raise ValueError("chamfer bracket has only {} faces (<60 required)".format(info_a["faces"]))

    # ---- B: pocket complex plate ------------------------------------------
    plate, pocket_meta, through_meta, deep_pockets = _build_pocket_plate()
    info_b = S.shape_info(plate)
    if info_b["solids"] != 1:
        raise ValueError("pocket plate: expected 1 solid, got {}".format(info_b["solids"]))
    path_b = outdir / "GeomCleanup_PocketComplex.step"
    S.export_step(plate, str(path_b), "GeomCleanup_PocketComplex")
    info_b2 = S.verify_step(str(path_b))
    if info_b2["solids"] != 1:
        raise ValueError("pocket plate step did not round-trip a solid")

    # pocket count assertions
    n_pockets = len(pocket_meta)
    n_through = len(through_meta)
    n_deep = len(deep_pockets)
    if n_pockets != 32 or n_through != 10 or n_deep != 2:
        raise ValueError("unexpected pocket counts: {} pockets / {} through / {} deep".format(
            n_pockets, n_through, n_deep))
    for m in pocket_meta:
        if not (m["cb_depth"] < 3.0 and m["cb_d"] > m["hole_d"]):
            raise ValueError("counterbore rule violated: {}".format(m))

    stats = {
        "files": 2,
        "chamfer_bracket_faces": info_a["faces"],
        "chamfer_bracket_bbox": info_a["bbox"],
        "applied_count": {"bosses": 5, "ribs": 3, "pads": 2, "holes": 8},
        "chamfer_range_mm": PARAMS["chamfer_range_mm"],
        "negative_fillet_radius_mm": PARAMS["negative_fillet_radius_mm"],
        "pockets": n_pockets,
        "through_holes": n_through,
        "deep_pockets_reject": n_deep,
        "pocket_plate_faces": info_b2["faces"],
        "pocket_plate_bbox": info_b2["bbox"],
        "parameters": PARAMS,
    }

    common.write_manifest(outdir / "geom_cleanup_multi_feature_manifest.json", {
        "module": "geometry_cleanup",
        "purpose": "LARGE STEP solids for geometry cleanup CHAMFER + POCKET repair",
        "generator": "tools/model_generation/gen_geom_cleanup.py",
        "parameters": PARAMS,
        "files": ["GeomCleanup_ChamferComplex.step", "GeomCleanup_PocketComplex.step"],
        "statistics": stats,
        "pockets": pocket_meta,
        "through_holes": through_meta,
        "deep_pockets_reject": deep_pockets,
    })
    common.write_readme(outdir / "README.md", README)

    print({
        "chamfer_bracket_faces": info_a["faces"],
        "pockets": n_pockets, "through": n_through,
        "deep_reject": n_deep, "pocket_plate_faces": info_b2["faces"],
    })
    return 0


README = """# geometry_cleanup — 大模型验证（CHAMFER + POCKET 两个场景）

## 用途
两个独立 .step（各含 1 个实体，导入后组件名 = 文件名），覆盖几何清理模块的
两大识别/修复场景：

| 文件 | 内容 | 预期 |
|---|---|---|
| GeomCleanup_ChamferComplex.step | 铸件风支架（100×80×30 主体 + 4 凸台 + 3 筋 + 底座法兰），边倒角 1~3mm、边圆角 r=0.5~5 混合，边缘含 1 处 r=7mm（>5）超范围负向；6 个通孔 | 种子面 → 链式扩展 → 删圆角/倒角面 → 可重建实体；r>5 边缘被拒绝 |
| GeomCleanup_PocketComplex.step | pocket_plate 200×150×6：32 沉台（深 1.0~2.5 < 3、沉孔半径 4~12 > 通孔半径 2~6，规则梯度）+ 10 普通通孔 + 2 个深 4mm（>3）负向 | 32 沉台+10 孔接受；2 深邃沉台被分类器拒绝 |

## 模块参数（生成时对齐）
`fillet_max_r=5`、`max_chain_depth=6`、`area_growth_ratio=2.5`、
`stitch_tolerance=0.2`。

## 操作
1. HyperMesh 逐个导入 `*.step`（单位 mm）。
2. geometry_cleanup 选择组件跑 CHAMFER 模式 / POCKET 模式。
3. 核对沉台数量、深邃负向组件是否被拒绝、修复后实体可重建。

## 设计说明
- 沉台 `cb_depth < t/2`（6/2=3）且 `cb_d > hole_d` 才被接受；深邃 cb_depth=4 > 3 应为 REJECT。
- ChamferComplex 含 >5mm 圆角负向；所有特征经逐边 try/except（半径递减）保证实体稳健且 solids==1。
- 每文件自检 solids==1；ChamferComplex 面数 ≥60。
"""


if __name__ == "__main__":
    raise SystemExit(main())
