# Audit HyperMesh Tcl command usage across the HW repository.
#
# Scans every .tcl file, extracts *command / hm_command tokens, classifies
# repo-defined procs, and emits:
#   - a per-module usage report (audit_hm_commands_report.txt / .json)
#   - tools/probe_hm_commands_existence.tcl for the headless hmbatch
#     existence probe (run one hmbatch per installed HyperMesh version).
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKEN = re.compile(r"(?<![A-Za-z0-9_])(\*[a-z][a-z0-9_]*|\bhm_[a-z][a-z0-9_]*)")
PROC = re.compile(r"^\s*proc\s+(\*?[A-Za-z0-9_:]+)", re.MULTILINE)


def scan() -> tuple[dict[str, set[str]], set[str]]:
    usage: dict[str, set[str]] = {}
    defined: set[str] = set()
    for path in sorted(list(ROOT.glob("modules/**/*.tcl")) + sorted(ROOT.glob("*.tcl"))):
        rel = path.relative_to(ROOT).as_posix()
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for name in TOKEN.findall(text):
            usage.setdefault(name, set()).add(rel)
        if "/tests/" not in rel:
            for match in PROC.finditer(text):
                # Normalize namespace-qualified names to the bare token.
                token = match.group(1).lstrip(":").split("::")[-1]
                if token:
                    defined.add(token)
    return usage, defined


def main() -> int:
    usage, defined = scan()
    native = {name: files for name, files in usage.items() if name not in defined}

    report = [f"# HyperMesh Tcl command audit ({len(native)} native candidates, "
              f"{len(usage)} distinct tokens)", ""]
    for name in sorted(native, key=lambda n: (n.startswith("hm_"), n.lower())):
        files = sorted(native[name])
        report.append(f"{name}  ({len(files)} file(s))")
        for f in files:
            report.append(f"    {f}")
    report.append("")
    report.append("# Repo-defined procs (excluded from the native probe):")
    for name in sorted(defined):
        report.append(f"    {name}")
    report.append("")

    out_txt = ROOT / "tools" / "audit_hm_commands_report.txt"
    out_txt.write_text("\n".join(report), encoding="utf-8")
    (ROOT / "tools" / "audit_hm_commands_report.json").write_text(
        json.dumps(
            {"native": {k: sorted(v) for k, v in sorted(native.items())},
             "defined": sorted(defined)},
            indent=2,
        ),
        encoding="utf-8",
    )

    probe = ROOT / "tools" / "probe_hm_commands_existence.tcl"
    lines = [
        "# Generated by tools/audit_hm_commands.py - do not edit by hand.",
        "# Headless existence probe: run one hmbatch per installed HyperMesh.",
        "set out [open hm_commands_existence.txt w]",
        "proc log {msg} {",
        "    global out",
        "    puts $out $msg",
        "    flush $out",
        "    catch {puts $msg}",
        "}",
        "catch {log [hm_info -appinfo VERSION]}",
        "set commands {",
    ]
    for name in sorted(native):
        lines.append(f"    {name}")
    lines += [
        "}",
        "foreach name $commands {",
        "    set pat [string map {* {\\*} ? {\\?} [ {\\[} ] {\\]} \\\\ {\\\\\\\\}} $name]",
        "    set has [expr {[llength [info commands $pat]] > 0}]",
        "    log [format \"%-40s %s\" $name [expr {$has ? \"EXIST\" : \"MISS\"}]]",
        "}",
        "close $out",
        "exit",
        "",
    ]
    probe.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_txt.name}, audit_hm_commands_report.json, {probe.name}")
    print(f"native candidates: {len(native)}, defined procs: {len(defined)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
